# Copyright (c) 2016 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: theExpeditionarium
site_description: Ideas as technology.
site_author: rapidExpedition
site_url: http://rapidExpedition.github.io/theExpeditionarium/

# Repository
repo_name: GitHub
repo_url: https://github.com/rapidExpedition/theExpeditionarium

# Copyright
copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

# Documentation and theme
theme_dir: material

# Options
extra:
  version: 0.2.4
  logo: images/logo.png
  author:
    github: rapidExpedition

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

# Page tree
pages:
  - Welcome: index.md
#  - rapidExpedition: rapidExpedition/About.md
#    - .fit: rapidExpedition/fitSum.md
#    - .edu: rapidExpedition/eduSum.md
#    - .hack: rapidExpedition/hackSum.md
#    - .mk: rapidExpedition/mkSum.md
#    - .ag: rapidExpedition/agSum.md
#    - .civ: rapidExpedition/civSum.md
#    - .pub: rapidExpedition/pubSum.md
  - wayPoint: wayPoint/About.md
#  - expeditionaryPhilosophy:
#  - contribute:
#    - [on GitHub](https://github.com/rapidExpedition/theExpeditionarium)
